version: 1

deploy:
  steps:
    setupVariables:
      after:
        - aws eks list-clusters --region us-east-1
        - awsv2 eks --region=us-east-1 update-kubeconfig --name ${ENV0_CLUSTER_NAME}
        - "sed -i 's/command: aws/command: awsv2/g' ~/.kube/config"
        - cat /home/node/.kube/config

destroy:
  steps:
    setupVariables:
      after:
        - awsv2 eks --region=us-east-1 update-kubeconfig --name ${ENV0_CLUSTER_NAME}
        - "sed -i 's/command: aws/command: awsv2/g' ~/.kube/config"
        - cat /home/node/.kube/config
